//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodusorClient.kodusorServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanicilar", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis.Models")]
    [System.SerializableAttribute()]
    public partial class Kullanicilar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Cevaplar[] CevaplarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.FavoriCevaplar[] FavoriCevaplarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.FavoriSorular[] FavoriSorularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GithubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HakkimdaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParolaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilFotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Sorular[] SorularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Yorum[] YorumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CepTel {
            get {
                return this.CepTelField;
            }
            set {
                if ((object.ReferenceEquals(this.CepTelField, value) != true)) {
                    this.CepTelField = value;
                    this.RaisePropertyChanged("CepTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Cevaplar[] Cevaplar {
            get {
                return this.CevaplarField;
            }
            set {
                if ((object.ReferenceEquals(this.CevaplarField, value) != true)) {
                    this.CevaplarField = value;
                    this.RaisePropertyChanged("Cevaplar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.FavoriCevaplar[] FavoriCevaplar {
            get {
                return this.FavoriCevaplarField;
            }
            set {
                if ((object.ReferenceEquals(this.FavoriCevaplarField, value) != true)) {
                    this.FavoriCevaplarField = value;
                    this.RaisePropertyChanged("FavoriCevaplar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.FavoriSorular[] FavoriSorular {
            get {
                return this.FavoriSorularField;
            }
            set {
                if ((object.ReferenceEquals(this.FavoriSorularField, value) != true)) {
                    this.FavoriSorularField = value;
                    this.RaisePropertyChanged("FavoriSorular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Github {
            get {
                return this.GithubField;
            }
            set {
                if ((object.ReferenceEquals(this.GithubField, value) != true)) {
                    this.GithubField = value;
                    this.RaisePropertyChanged("Github");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hakkimda {
            get {
                return this.HakkimdaField;
            }
            set {
                if ((object.ReferenceEquals(this.HakkimdaField, value) != true)) {
                    this.HakkimdaField = value;
                    this.RaisePropertyChanged("Hakkimda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Linkedin {
            get {
                return this.LinkedinField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedinField, value) != true)) {
                    this.LinkedinField = value;
                    this.RaisePropertyChanged("Linkedin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parola {
            get {
                return this.ParolaField;
            }
            set {
                if ((object.ReferenceEquals(this.ParolaField, value) != true)) {
                    this.ParolaField = value;
                    this.RaisePropertyChanged("Parola");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilFoto {
            get {
                return this.ProfilFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilFotoField, value) != true)) {
                    this.ProfilFotoField = value;
                    this.RaisePropertyChanged("ProfilFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Sorular[] Sorular {
            get {
                return this.SorularField;
            }
            set {
                if ((object.ReferenceEquals(this.SorularField, value) != true)) {
                    this.SorularField = value;
                    this.RaisePropertyChanged("Sorular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyadi {
            get {
                return this.SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadiField, value) != true)) {
                    this.SoyadiField = value;
                    this.RaisePropertyChanged("Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Yorum[] Yorum {
            get {
                return this.YorumField;
            }
            set {
                if ((object.ReferenceEquals(this.YorumField, value) != true)) {
                    this.YorumField = value;
                    this.RaisePropertyChanged("Yorum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cevaplar", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis.Models")]
    [System.SerializableAttribute()]
    public partial class Cevaplar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BegeniSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CevapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CevapIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.FavoriCevaplar[] FavoriCevaplarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Kullanicilar KullanicilarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoruIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Sorular SorularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Yorum[] YorumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BegeniSayisi {
            get {
                return this.BegeniSayisiField;
            }
            set {
                if ((this.BegeniSayisiField.Equals(value) != true)) {
                    this.BegeniSayisiField = value;
                    this.RaisePropertyChanged("BegeniSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cevap {
            get {
                return this.CevapField;
            }
            set {
                if ((object.ReferenceEquals(this.CevapField, value) != true)) {
                    this.CevapField = value;
                    this.RaisePropertyChanged("Cevap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CevapID {
            get {
                return this.CevapIDField;
            }
            set {
                if ((this.CevapIDField.Equals(value) != true)) {
                    this.CevapIDField = value;
                    this.RaisePropertyChanged("CevapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.FavoriCevaplar[] FavoriCevaplar {
            get {
                return this.FavoriCevaplarField;
            }
            set {
                if ((object.ReferenceEquals(this.FavoriCevaplarField, value) != true)) {
                    this.FavoriCevaplarField = value;
                    this.RaisePropertyChanged("FavoriCevaplar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Kullanicilar Kullanicilar {
            get {
                return this.KullanicilarField;
            }
            set {
                if ((object.ReferenceEquals(this.KullanicilarField, value) != true)) {
                    this.KullanicilarField = value;
                    this.RaisePropertyChanged("Kullanicilar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoruID {
            get {
                return this.SoruIDField;
            }
            set {
                if ((this.SoruIDField.Equals(value) != true)) {
                    this.SoruIDField = value;
                    this.RaisePropertyChanged("SoruID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Sorular Sorular {
            get {
                return this.SorularField;
            }
            set {
                if ((object.ReferenceEquals(this.SorularField, value) != true)) {
                    this.SorularField = value;
                    this.RaisePropertyChanged("Sorular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Yorum[] Yorum {
            get {
                return this.YorumField;
            }
            set {
                if ((object.ReferenceEquals(this.YorumField, value) != true)) {
                    this.YorumField = value;
                    this.RaisePropertyChanged("Yorum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FavoriCevaplar", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis.Models")]
    [System.SerializableAttribute()]
    public partial class FavoriCevaplar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CevapIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Cevaplar CevaplarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Kullanicilar KullanicilarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CevapID {
            get {
                return this.CevapIDField;
            }
            set {
                if ((this.CevapIDField.Equals(value) != true)) {
                    this.CevapIDField = value;
                    this.RaisePropertyChanged("CevapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Cevaplar Cevaplar {
            get {
                return this.CevaplarField;
            }
            set {
                if ((object.ReferenceEquals(this.CevaplarField, value) != true)) {
                    this.CevaplarField = value;
                    this.RaisePropertyChanged("Cevaplar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Kullanicilar Kullanicilar {
            get {
                return this.KullanicilarField;
            }
            set {
                if ((object.ReferenceEquals(this.KullanicilarField, value) != true)) {
                    this.KullanicilarField = value;
                    this.RaisePropertyChanged("Kullanicilar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FavoriSorular", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis.Models")]
    [System.SerializableAttribute()]
    public partial class FavoriSorular : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Kullanicilar KullanicilarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoruIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Sorular SorularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Kullanicilar Kullanicilar {
            get {
                return this.KullanicilarField;
            }
            set {
                if ((object.ReferenceEquals(this.KullanicilarField, value) != true)) {
                    this.KullanicilarField = value;
                    this.RaisePropertyChanged("Kullanicilar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoruID {
            get {
                return this.SoruIDField;
            }
            set {
                if ((this.SoruIDField.Equals(value) != true)) {
                    this.SoruIDField = value;
                    this.RaisePropertyChanged("SoruID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Sorular Sorular {
            get {
                return this.SorularField;
            }
            set {
                if ((object.ReferenceEquals(this.SorularField, value) != true)) {
                    this.SorularField = value;
                    this.RaisePropertyChanged("Sorular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sorular", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis.Models")]
    [System.SerializableAttribute()]
    public partial class Sorular : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaslikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BegeniSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Cevaplar[] CevaplarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.FavoriSorular[] FavoriSorularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcerikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Kullanicilar KullanicilarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OnayCevapIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.SoruEtiket[] SoruEtiketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoruIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TarihField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Baslik {
            get {
                return this.BaslikField;
            }
            set {
                if ((object.ReferenceEquals(this.BaslikField, value) != true)) {
                    this.BaslikField = value;
                    this.RaisePropertyChanged("Baslik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BegeniSayisi {
            get {
                return this.BegeniSayisiField;
            }
            set {
                if ((this.BegeniSayisiField.Equals(value) != true)) {
                    this.BegeniSayisiField = value;
                    this.RaisePropertyChanged("BegeniSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Cevaplar[] Cevaplar {
            get {
                return this.CevaplarField;
            }
            set {
                if ((object.ReferenceEquals(this.CevaplarField, value) != true)) {
                    this.CevaplarField = value;
                    this.RaisePropertyChanged("Cevaplar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.FavoriSorular[] FavoriSorular {
            get {
                return this.FavoriSorularField;
            }
            set {
                if ((object.ReferenceEquals(this.FavoriSorularField, value) != true)) {
                    this.FavoriSorularField = value;
                    this.RaisePropertyChanged("FavoriSorular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icerik {
            get {
                return this.IcerikField;
            }
            set {
                if ((object.ReferenceEquals(this.IcerikField, value) != true)) {
                    this.IcerikField = value;
                    this.RaisePropertyChanged("Icerik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Kullanicilar Kullanicilar {
            get {
                return this.KullanicilarField;
            }
            set {
                if ((object.ReferenceEquals(this.KullanicilarField, value) != true)) {
                    this.KullanicilarField = value;
                    this.RaisePropertyChanged("Kullanicilar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OnayCevapID {
            get {
                return this.OnayCevapIDField;
            }
            set {
                if ((this.OnayCevapIDField.Equals(value) != true)) {
                    this.OnayCevapIDField = value;
                    this.RaisePropertyChanged("OnayCevapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.SoruEtiket[] SoruEtiket {
            get {
                return this.SoruEtiketField;
            }
            set {
                if ((object.ReferenceEquals(this.SoruEtiketField, value) != true)) {
                    this.SoruEtiketField = value;
                    this.RaisePropertyChanged("SoruEtiket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoruID {
            get {
                return this.SoruIDField;
            }
            set {
                if ((this.SoruIDField.Equals(value) != true)) {
                    this.SoruIDField = value;
                    this.RaisePropertyChanged("SoruID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yorum", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis.Models")]
    [System.SerializableAttribute()]
    public partial class Yorum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CevapIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Cevaplar CevaplarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Kullanicilar KullanicilarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Yorum1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YorumIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CevapID {
            get {
                return this.CevapIDField;
            }
            set {
                if ((this.CevapIDField.Equals(value) != true)) {
                    this.CevapIDField = value;
                    this.RaisePropertyChanged("CevapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Cevaplar Cevaplar {
            get {
                return this.CevaplarField;
            }
            set {
                if ((object.ReferenceEquals(this.CevaplarField, value) != true)) {
                    this.CevaplarField = value;
                    this.RaisePropertyChanged("Cevaplar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Kullanicilar Kullanicilar {
            get {
                return this.KullanicilarField;
            }
            set {
                if ((object.ReferenceEquals(this.KullanicilarField, value) != true)) {
                    this.KullanicilarField = value;
                    this.RaisePropertyChanged("Kullanicilar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Yorum1 {
            get {
                return this.Yorum1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Yorum1Field, value) != true)) {
                    this.Yorum1Field = value;
                    this.RaisePropertyChanged("Yorum1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YorumID {
            get {
                return this.YorumIDField;
            }
            set {
                if ((this.YorumIDField.Equals(value) != true)) {
                    this.YorumIDField = value;
                    this.RaisePropertyChanged("YorumID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoruEtiket", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis.Models")]
    [System.SerializableAttribute()]
    public partial class SoruEtiket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EtiketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Etiketler EtiketlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoruIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.Sorular SorularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EtiketID {
            get {
                return this.EtiketIDField;
            }
            set {
                if ((this.EtiketIDField.Equals(value) != true)) {
                    this.EtiketIDField = value;
                    this.RaisePropertyChanged("EtiketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Etiketler Etiketler {
            get {
                return this.EtiketlerField;
            }
            set {
                if ((object.ReferenceEquals(this.EtiketlerField, value) != true)) {
                    this.EtiketlerField = value;
                    this.RaisePropertyChanged("Etiketler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoruID {
            get {
                return this.SoruIDField;
            }
            set {
                if ((this.SoruIDField.Equals(value) != true)) {
                    this.SoruIDField = value;
                    this.RaisePropertyChanged("SoruID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.Sorular Sorular {
            get {
                return this.SorularField;
            }
            set {
                if ((object.ReferenceEquals(this.SorularField, value) != true)) {
                    this.SorularField = value;
                    this.RaisePropertyChanged("Sorular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Etiketler", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis.Models")]
    [System.SerializableAttribute()]
    public partial class Etiketler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtiketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EtiketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.SoruEtiket[] SoruEtiketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EtiketAdi {
            get {
                return this.EtiketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.EtiketAdiField, value) != true)) {
                    this.EtiketAdiField = value;
                    this.RaisePropertyChanged("EtiketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EtiketID {
            get {
                return this.EtiketIDField;
            }
            set {
                if ((this.EtiketIDField.Equals(value) != true)) {
                    this.EtiketIDField = value;
                    this.RaisePropertyChanged("EtiketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.SoruEtiket[] SoruEtiket {
            get {
                return this.SoruEtiketField;
            }
            set {
                if ((object.ReferenceEquals(this.SoruEtiketField, value) != true)) {
                    this.SoruEtiketField = value;
                    this.RaisePropertyChanged("SoruEtiket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoruListesi", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis")]
    [System.SerializableAttribute()]
    public partial class SoruListesi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaslikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BegeniSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CevapSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.CevapListesi[] CevaplarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.EtiketListesi[] EtiketlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcerikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.kullaniciListesi KullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OnayCevapIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoruIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TarihField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Baslik {
            get {
                return this.BaslikField;
            }
            set {
                if ((object.ReferenceEquals(this.BaslikField, value) != true)) {
                    this.BaslikField = value;
                    this.RaisePropertyChanged("Baslik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BegeniSayisi {
            get {
                return this.BegeniSayisiField;
            }
            set {
                if ((this.BegeniSayisiField.Equals(value) != true)) {
                    this.BegeniSayisiField = value;
                    this.RaisePropertyChanged("BegeniSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CevapSayisi {
            get {
                return this.CevapSayisiField;
            }
            set {
                if ((this.CevapSayisiField.Equals(value) != true)) {
                    this.CevapSayisiField = value;
                    this.RaisePropertyChanged("CevapSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.CevapListesi[] Cevaplar {
            get {
                return this.CevaplarField;
            }
            set {
                if ((object.ReferenceEquals(this.CevaplarField, value) != true)) {
                    this.CevaplarField = value;
                    this.RaisePropertyChanged("Cevaplar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.EtiketListesi[] Etiketler {
            get {
                return this.EtiketlerField;
            }
            set {
                if ((object.ReferenceEquals(this.EtiketlerField, value) != true)) {
                    this.EtiketlerField = value;
                    this.RaisePropertyChanged("Etiketler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icerik {
            get {
                return this.IcerikField;
            }
            set {
                if ((object.ReferenceEquals(this.IcerikField, value) != true)) {
                    this.IcerikField = value;
                    this.RaisePropertyChanged("Icerik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.kullaniciListesi Kullanici {
            get {
                return this.KullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciField, value) != true)) {
                    this.KullaniciField = value;
                    this.RaisePropertyChanged("Kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OnayCevapID {
            get {
                return this.OnayCevapIDField;
            }
            set {
                if ((this.OnayCevapIDField.Equals(value) != true)) {
                    this.OnayCevapIDField = value;
                    this.RaisePropertyChanged("OnayCevapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoruID {
            get {
                return this.SoruIDField;
            }
            set {
                if ((this.SoruIDField.Equals(value) != true)) {
                    this.SoruIDField = value;
                    this.RaisePropertyChanged("SoruID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kullaniciListesi", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis")]
    [System.SerializableAttribute()]
    public partial class kullaniciListesi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CeptelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GithubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HakkimdaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParolaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilFotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ceptel {
            get {
                return this.CeptelField;
            }
            set {
                if ((object.ReferenceEquals(this.CeptelField, value) != true)) {
                    this.CeptelField = value;
                    this.RaisePropertyChanged("Ceptel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Github {
            get {
                return this.GithubField;
            }
            set {
                if ((object.ReferenceEquals(this.GithubField, value) != true)) {
                    this.GithubField = value;
                    this.RaisePropertyChanged("Github");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hakkimda {
            get {
                return this.HakkimdaField;
            }
            set {
                if ((object.ReferenceEquals(this.HakkimdaField, value) != true)) {
                    this.HakkimdaField = value;
                    this.RaisePropertyChanged("Hakkimda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Linkedin {
            get {
                return this.LinkedinField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedinField, value) != true)) {
                    this.LinkedinField = value;
                    this.RaisePropertyChanged("Linkedin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parola {
            get {
                return this.ParolaField;
            }
            set {
                if ((object.ReferenceEquals(this.ParolaField, value) != true)) {
                    this.ParolaField = value;
                    this.RaisePropertyChanged("Parola");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilFoto {
            get {
                return this.ProfilFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilFotoField, value) != true)) {
                    this.ProfilFotoField = value;
                    this.RaisePropertyChanged("ProfilFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyadi {
            get {
                return this.SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadiField, value) != true)) {
                    this.SoyadiField = value;
                    this.RaisePropertyChanged("Soyadi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CevapListesi", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis")]
    [System.SerializableAttribute()]
    public partial class CevapListesi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BegeniSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CevapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CevapIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoruIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.SoruListesi SorularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kodusorClient.kodusorServis.YorumListesi[] YorumListesiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BegeniSayisi {
            get {
                return this.BegeniSayisiField;
            }
            set {
                if ((this.BegeniSayisiField.Equals(value) != true)) {
                    this.BegeniSayisiField = value;
                    this.RaisePropertyChanged("BegeniSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cevap {
            get {
                return this.CevapField;
            }
            set {
                if ((object.ReferenceEquals(this.CevapField, value) != true)) {
                    this.CevapField = value;
                    this.RaisePropertyChanged("Cevap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CevapID {
            get {
                return this.CevapIDField;
            }
            set {
                if ((this.CevapIDField.Equals(value) != true)) {
                    this.CevapIDField = value;
                    this.RaisePropertyChanged("CevapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoruID {
            get {
                return this.SoruIDField;
            }
            set {
                if ((this.SoruIDField.Equals(value) != true)) {
                    this.SoruIDField = value;
                    this.RaisePropertyChanged("SoruID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.SoruListesi Sorular {
            get {
                return this.SorularField;
            }
            set {
                if ((object.ReferenceEquals(this.SorularField, value) != true)) {
                    this.SorularField = value;
                    this.RaisePropertyChanged("Sorular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kodusorClient.kodusorServis.YorumListesi[] YorumListesi {
            get {
                return this.YorumListesiField;
            }
            set {
                if ((object.ReferenceEquals(this.YorumListesiField, value) != true)) {
                    this.YorumListesiField = value;
                    this.RaisePropertyChanged("YorumListesi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EtiketListesi", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis")]
    [System.SerializableAttribute()]
    public partial class EtiketListesi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtiketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EtiketIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EtiketAdi {
            get {
                return this.EtiketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.EtiketAdiField, value) != true)) {
                    this.EtiketAdiField = value;
                    this.RaisePropertyChanged("EtiketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EtiketID {
            get {
                return this.EtiketIDField;
            }
            set {
                if ((this.EtiketIDField.Equals(value) != true)) {
                    this.EtiketIDField = value;
                    this.RaisePropertyChanged("EtiketID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YorumListesi", Namespace="http://schemas.datacontract.org/2004/07/kodusorServis")]
    [System.SerializableAttribute()]
    public partial class YorumListesi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YorumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YorumIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Yorum {
            get {
                return this.YorumField;
            }
            set {
                if ((object.ReferenceEquals(this.YorumField, value) != true)) {
                    this.YorumField = value;
                    this.RaisePropertyChanged("Yorum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YorumID {
            get {
                return this.YorumIDField;
            }
            set {
                if ((this.YorumIDField.Equals(value) != true)) {
                    this.YorumIDField = value;
                    this.RaisePropertyChanged("YorumID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="kodusorServis.IKodusorServis")]
    public interface IKodusorServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/GetData", ReplyAction="http://tempuri.org/IKodusorServis/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/GetData", ReplyAction="http://tempuri.org/IKodusorServis/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KayitOl", ReplyAction="http://tempuri.org/IKodusorServis/KayitOlResponse")]
        string KayitOl(kodusorClient.kodusorServis.Kullanicilar kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KayitOl", ReplyAction="http://tempuri.org/IKodusorServis/KayitOlResponse")]
        System.Threading.Tasks.Task<string> KayitOlAsync(kodusorClient.kodusorServis.Kullanicilar kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SorulariListele", ReplyAction="http://tempuri.org/IKodusorServis/SorulariListeleResponse")]
        kodusorClient.kodusorServis.SoruListesi[] SorulariListele(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SorulariListele", ReplyAction="http://tempuri.org/IKodusorServis/SorulariListeleResponse")]
        System.Threading.Tasks.Task<kodusorClient.kodusorServis.SoruListesi[]> SorulariListeleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/GirisYap", ReplyAction="http://tempuri.org/IKodusorServis/GirisYapResponse")]
        int GirisYap(string mail, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/GirisYap", ReplyAction="http://tempuri.org/IKodusorServis/GirisYapResponse")]
        System.Threading.Tasks.Task<int> GirisYapAsync(string mail, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullaniciCevapları", ReplyAction="http://tempuri.org/IKodusorServis/KullaniciCevaplarıResponse")]
        kodusorClient.kodusorServis.CevapListesi[] KullaniciCevapları(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullaniciCevapları", ReplyAction="http://tempuri.org/IKodusorServis/KullaniciCevaplarıResponse")]
        System.Threading.Tasks.Task<kodusorClient.kodusorServis.CevapListesi[]> KullaniciCevaplarıAsync(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/FavoriSorular", ReplyAction="http://tempuri.org/IKodusorServis/FavoriSorularResponse")]
        kodusorClient.kodusorServis.SoruListesi[] FavoriSorular(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/FavoriSorular", ReplyAction="http://tempuri.org/IKodusorServis/FavoriSorularResponse")]
        System.Threading.Tasks.Task<kodusorClient.kodusorServis.SoruListesi[]> FavoriSorularAsync(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/FavoriCevaplar", ReplyAction="http://tempuri.org/IKodusorServis/FavoriCevaplarResponse")]
        kodusorClient.kodusorServis.CevapListesi[] FavoriCevaplar(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/FavoriCevaplar", ReplyAction="http://tempuri.org/IKodusorServis/FavoriCevaplarResponse")]
        System.Threading.Tasks.Task<kodusorClient.kodusorServis.CevapListesi[]> FavoriCevaplarAsync(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullanicininEtiketleri", ReplyAction="http://tempuri.org/IKodusorServis/KullanicininEtiketleriResponse")]
        kodusorClient.kodusorServis.EtiketListesi[] KullanicininEtiketleri(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullanicininEtiketleri", ReplyAction="http://tempuri.org/IKodusorServis/KullanicininEtiketleriResponse")]
        System.Threading.Tasks.Task<kodusorClient.kodusorServis.EtiketListesi[]> KullanicininEtiketleriAsync(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullaniciBilgileriGuncelle", ReplyAction="http://tempuri.org/IKodusorServis/KullaniciBilgileriGuncelleResponse")]
        bool KullaniciBilgileriGuncelle(kodusorClient.kodusorServis.Kullanicilar kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullaniciBilgileriGuncelle", ReplyAction="http://tempuri.org/IKodusorServis/KullaniciBilgileriGuncelleResponse")]
        System.Threading.Tasks.Task<bool> KullaniciBilgileriGuncelleAsync(kodusorClient.kodusorServis.Kullanicilar kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/ParolaDegistir", ReplyAction="http://tempuri.org/IKodusorServis/ParolaDegistirResponse")]
        bool ParolaDegistir(int kullaniciID, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/ParolaDegistir", ReplyAction="http://tempuri.org/IKodusorServis/ParolaDegistirResponse")]
        System.Threading.Tasks.Task<bool> ParolaDegistirAsync(int kullaniciID, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullaniciBilgileriniGetir", ReplyAction="http://tempuri.org/IKodusorServis/KullaniciBilgileriniGetirResponse")]
        kodusorClient.kodusorServis.kullaniciListesi KullaniciBilgileriniGetir(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullaniciBilgileriniGetir", ReplyAction="http://tempuri.org/IKodusorServis/KullaniciBilgileriniGetirResponse")]
        System.Threading.Tasks.Task<kodusorClient.kodusorServis.kullaniciListesi> KullaniciBilgileriniGetirAsync(int kullaniciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SoruEkle", ReplyAction="http://tempuri.org/IKodusorServis/SoruEkleResponse")]
        bool SoruEkle(int kullaniciID, kodusorClient.kodusorServis.Sorular soru, kodusorClient.kodusorServis.Etiketler[] etiketler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SoruEkle", ReplyAction="http://tempuri.org/IKodusorServis/SoruEkleResponse")]
        System.Threading.Tasks.Task<bool> SoruEkleAsync(int kullaniciID, kodusorClient.kodusorServis.Sorular soru, kodusorClient.kodusorServis.Etiketler[] etiketler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SoruSil", ReplyAction="http://tempuri.org/IKodusorServis/SoruSilResponse")]
        bool SoruSil(int kullaniciID, int soruID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SoruSil", ReplyAction="http://tempuri.org/IKodusorServis/SoruSilResponse")]
        System.Threading.Tasks.Task<bool> SoruSilAsync(int kullaniciID, int soruID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/CevapEkle", ReplyAction="http://tempuri.org/IKodusorServis/CevapEkleResponse")]
        bool CevapEkle(kodusorClient.kodusorServis.Cevaplar cevap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/CevapEkle", ReplyAction="http://tempuri.org/IKodusorServis/CevapEkleResponse")]
        System.Threading.Tasks.Task<bool> CevapEkleAsync(kodusorClient.kodusorServis.Cevaplar cevap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/YorumEkle", ReplyAction="http://tempuri.org/IKodusorServis/YorumEkleResponse")]
        bool YorumEkle(kodusorClient.kodusorServis.Yorum yourum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/YorumEkle", ReplyAction="http://tempuri.org/IKodusorServis/YorumEkleResponse")]
        System.Threading.Tasks.Task<bool> YorumEkleAsync(kodusorClient.kodusorServis.Yorum yourum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SoruyuFavoriyeEkle", ReplyAction="http://tempuri.org/IKodusorServis/SoruyuFavoriyeEkleResponse")]
        bool SoruyuFavoriyeEkle(kodusorClient.kodusorServis.FavoriSorular favoriSorular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SoruyuFavoriyeEkle", ReplyAction="http://tempuri.org/IKodusorServis/SoruyuFavoriyeEkleResponse")]
        System.Threading.Tasks.Task<bool> SoruyuFavoriyeEkleAsync(kodusorClient.kodusorServis.FavoriSorular favoriSorular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/CevabiFavoriyeEkle", ReplyAction="http://tempuri.org/IKodusorServis/CevabiFavoriyeEkleResponse")]
        bool CevabiFavoriyeEkle(kodusorClient.kodusorServis.FavoriCevaplar favoriCevaplar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/CevabiFavoriyeEkle", ReplyAction="http://tempuri.org/IKodusorServis/CevabiFavoriyeEkleResponse")]
        System.Threading.Tasks.Task<bool> CevabiFavoriyeEkleAsync(kodusorClient.kodusorServis.FavoriCevaplar favoriCevaplar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/CevabıOnayla", ReplyAction="http://tempuri.org/IKodusorServis/CevabıOnaylaResponse")]
        bool CevabıOnayla(int soruID, int cevapID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/CevabıOnayla", ReplyAction="http://tempuri.org/IKodusorServis/CevabıOnaylaResponse")]
        System.Threading.Tasks.Task<bool> CevabıOnaylaAsync(int soruID, int cevapID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SoruGetir", ReplyAction="http://tempuri.org/IKodusorServis/SoruGetirResponse")]
        kodusorClient.kodusorServis.SoruListesi SoruGetir(int soruID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/SoruGetir", ReplyAction="http://tempuri.org/IKodusorServis/SoruGetirResponse")]
        System.Threading.Tasks.Task<kodusorClient.kodusorServis.SoruListesi> SoruGetirAsync(int soruID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullanicilariListele", ReplyAction="http://tempuri.org/IKodusorServis/KullanicilariListeleResponse")]
        kodusorClient.kodusorServis.kullaniciListesi[] KullanicilariListele();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKodusorServis/KullanicilariListele", ReplyAction="http://tempuri.org/IKodusorServis/KullanicilariListeleResponse")]
        System.Threading.Tasks.Task<kodusorClient.kodusorServis.kullaniciListesi[]> KullanicilariListeleAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKodusorServisChannel : kodusorClient.kodusorServis.IKodusorServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KodusorServisClient : System.ServiceModel.ClientBase<kodusorClient.kodusorServis.IKodusorServis>, kodusorClient.kodusorServis.IKodusorServis {
        
        public KodusorServisClient() {
        }
        
        public KodusorServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KodusorServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KodusorServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KodusorServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string KayitOl(kodusorClient.kodusorServis.Kullanicilar kullanici) {
            return base.Channel.KayitOl(kullanici);
        }
        
        public System.Threading.Tasks.Task<string> KayitOlAsync(kodusorClient.kodusorServis.Kullanicilar kullanici) {
            return base.Channel.KayitOlAsync(kullanici);
        }
        
        public kodusorClient.kodusorServis.SoruListesi[] SorulariListele(int id) {
            return base.Channel.SorulariListele(id);
        }
        
        public System.Threading.Tasks.Task<kodusorClient.kodusorServis.SoruListesi[]> SorulariListeleAsync(int id) {
            return base.Channel.SorulariListeleAsync(id);
        }
        
        public int GirisYap(string mail, string parola) {
            return base.Channel.GirisYap(mail, parola);
        }
        
        public System.Threading.Tasks.Task<int> GirisYapAsync(string mail, string parola) {
            return base.Channel.GirisYapAsync(mail, parola);
        }
        
        public kodusorClient.kodusorServis.CevapListesi[] KullaniciCevapları(int kullaniciID) {
            return base.Channel.KullaniciCevapları(kullaniciID);
        }
        
        public System.Threading.Tasks.Task<kodusorClient.kodusorServis.CevapListesi[]> KullaniciCevaplarıAsync(int kullaniciID) {
            return base.Channel.KullaniciCevaplarıAsync(kullaniciID);
        }
        
        public kodusorClient.kodusorServis.SoruListesi[] FavoriSorular(int kullaniciID) {
            return base.Channel.FavoriSorular(kullaniciID);
        }
        
        public System.Threading.Tasks.Task<kodusorClient.kodusorServis.SoruListesi[]> FavoriSorularAsync(int kullaniciID) {
            return base.Channel.FavoriSorularAsync(kullaniciID);
        }
        
        public kodusorClient.kodusorServis.CevapListesi[] FavoriCevaplar(int kullaniciID) {
            return base.Channel.FavoriCevaplar(kullaniciID);
        }
        
        public System.Threading.Tasks.Task<kodusorClient.kodusorServis.CevapListesi[]> FavoriCevaplarAsync(int kullaniciID) {
            return base.Channel.FavoriCevaplarAsync(kullaniciID);
        }
        
        public kodusorClient.kodusorServis.EtiketListesi[] KullanicininEtiketleri(int kullaniciID) {
            return base.Channel.KullanicininEtiketleri(kullaniciID);
        }
        
        public System.Threading.Tasks.Task<kodusorClient.kodusorServis.EtiketListesi[]> KullanicininEtiketleriAsync(int kullaniciID) {
            return base.Channel.KullanicininEtiketleriAsync(kullaniciID);
        }
        
        public bool KullaniciBilgileriGuncelle(kodusorClient.kodusorServis.Kullanicilar kullanici) {
            return base.Channel.KullaniciBilgileriGuncelle(kullanici);
        }
        
        public System.Threading.Tasks.Task<bool> KullaniciBilgileriGuncelleAsync(kodusorClient.kodusorServis.Kullanicilar kullanici) {
            return base.Channel.KullaniciBilgileriGuncelleAsync(kullanici);
        }
        
        public bool ParolaDegistir(int kullaniciID, string parola) {
            return base.Channel.ParolaDegistir(kullaniciID, parola);
        }
        
        public System.Threading.Tasks.Task<bool> ParolaDegistirAsync(int kullaniciID, string parola) {
            return base.Channel.ParolaDegistirAsync(kullaniciID, parola);
        }
        
        public kodusorClient.kodusorServis.kullaniciListesi KullaniciBilgileriniGetir(int kullaniciID) {
            return base.Channel.KullaniciBilgileriniGetir(kullaniciID);
        }
        
        public System.Threading.Tasks.Task<kodusorClient.kodusorServis.kullaniciListesi> KullaniciBilgileriniGetirAsync(int kullaniciID) {
            return base.Channel.KullaniciBilgileriniGetirAsync(kullaniciID);
        }
        
        public bool SoruEkle(int kullaniciID, kodusorClient.kodusorServis.Sorular soru, kodusorClient.kodusorServis.Etiketler[] etiketler) {
            return base.Channel.SoruEkle(kullaniciID, soru, etiketler);
        }
        
        public System.Threading.Tasks.Task<bool> SoruEkleAsync(int kullaniciID, kodusorClient.kodusorServis.Sorular soru, kodusorClient.kodusorServis.Etiketler[] etiketler) {
            return base.Channel.SoruEkleAsync(kullaniciID, soru, etiketler);
        }
        
        public bool SoruSil(int kullaniciID, int soruID) {
            return base.Channel.SoruSil(kullaniciID, soruID);
        }
        
        public System.Threading.Tasks.Task<bool> SoruSilAsync(int kullaniciID, int soruID) {
            return base.Channel.SoruSilAsync(kullaniciID, soruID);
        }
        
        public bool CevapEkle(kodusorClient.kodusorServis.Cevaplar cevap) {
            return base.Channel.CevapEkle(cevap);
        }
        
        public System.Threading.Tasks.Task<bool> CevapEkleAsync(kodusorClient.kodusorServis.Cevaplar cevap) {
            return base.Channel.CevapEkleAsync(cevap);
        }
        
        public bool YorumEkle(kodusorClient.kodusorServis.Yorum yourum) {
            return base.Channel.YorumEkle(yourum);
        }
        
        public System.Threading.Tasks.Task<bool> YorumEkleAsync(kodusorClient.kodusorServis.Yorum yourum) {
            return base.Channel.YorumEkleAsync(yourum);
        }
        
        public bool SoruyuFavoriyeEkle(kodusorClient.kodusorServis.FavoriSorular favoriSorular) {
            return base.Channel.SoruyuFavoriyeEkle(favoriSorular);
        }
        
        public System.Threading.Tasks.Task<bool> SoruyuFavoriyeEkleAsync(kodusorClient.kodusorServis.FavoriSorular favoriSorular) {
            return base.Channel.SoruyuFavoriyeEkleAsync(favoriSorular);
        }
        
        public bool CevabiFavoriyeEkle(kodusorClient.kodusorServis.FavoriCevaplar favoriCevaplar) {
            return base.Channel.CevabiFavoriyeEkle(favoriCevaplar);
        }
        
        public System.Threading.Tasks.Task<bool> CevabiFavoriyeEkleAsync(kodusorClient.kodusorServis.FavoriCevaplar favoriCevaplar) {
            return base.Channel.CevabiFavoriyeEkleAsync(favoriCevaplar);
        }
        
        public bool CevabıOnayla(int soruID, int cevapID) {
            return base.Channel.CevabıOnayla(soruID, cevapID);
        }
        
        public System.Threading.Tasks.Task<bool> CevabıOnaylaAsync(int soruID, int cevapID) {
            return base.Channel.CevabıOnaylaAsync(soruID, cevapID);
        }
        
        public kodusorClient.kodusorServis.SoruListesi SoruGetir(int soruID) {
            return base.Channel.SoruGetir(soruID);
        }
        
        public System.Threading.Tasks.Task<kodusorClient.kodusorServis.SoruListesi> SoruGetirAsync(int soruID) {
            return base.Channel.SoruGetirAsync(soruID);
        }
        
        public kodusorClient.kodusorServis.kullaniciListesi[] KullanicilariListele() {
            return base.Channel.KullanicilariListele();
        }
        
        public System.Threading.Tasks.Task<kodusorClient.kodusorServis.kullaniciListesi[]> KullanicilariListeleAsync() {
            return base.Channel.KullanicilariListeleAsync();
        }
    }
}
