//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodusorServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cevaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cevaplar()
        {
            this.FavoriCevaplar = new HashSet<FavoriCevaplar>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int CevapID { get; set; }
        public int SoruID { get; set; }
        public int KullaniciID { get; set; }
        public string Cevap { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> BegeniSayisi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Sorular Sorular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriCevaplar> FavoriCevaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
