//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodusorService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cevaplar
    {
        public Cevaplar()
        {
            this.Yorum = new HashSet<Yorum>();
            this.Kullanicilar1 = new HashSet<Kullanicilar>();
        }
    
        public int CevapID { get; set; }
        public int SoruID { get; set; }
        public int KullaniciID { get; set; }
        public string Cevap { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> BegeniSayisi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Sorular Sorular { get; set; }
        public virtual ICollection<Yorum> Yorum { get; set; }
        public virtual ICollection<Kullanicilar> Kullanicilar1 { get; set; }
    }
}
