//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodusorService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etiketler
    {
        public Etiketler()
        {
            this.Sorular = new HashSet<Sorular>();
        }
    
        public int EtiketID { get; set; }
        public string EtiketAdi { get; set; }
    
        public virtual ICollection<Sorular> Sorular { get; set; }
    }
}
