//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodusorServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class IletisimBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IletisimBilgileri()
        {
            this.Kullanicilar = new HashSet<Kullanicilar>();
        }
    
        public int IletisimBilgileriID { get; set; }
        public string Website { get; set; }
        public string Twitter { get; set; }
        public string Github { get; set; }
        public string Linkedin { get; set; }
        public string CepTel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilar { get; set; }
    }
}
