//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodusorServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoruEtiket
    {
        public int ID { get; set; }
        public int SoruID { get; set; }
        public int EtiketID { get; set; }
    
        public virtual Etiketler Etiketler { get; set; }
        public virtual Sorular Sorular { get; set; }
    }
}
