//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodusorServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sorular()
        {
            this.Cevaplar = new HashSet<Cevaplar>();
            this.FavoriSorular = new HashSet<FavoriSorular>();
            this.SoruEtiket = new HashSet<SoruEtiket>();
        }
    
        public int SoruID { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> BegeniSayisi { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<int> OnayCevapID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cevaplar> Cevaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriSorular> FavoriSorular { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruEtiket> SoruEtiket { get; set; }
    }
}
