//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kodusorEntities : DbContext
    {
        public kodusorEntities()
            : base("name=kodusorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cevaplar> Cevaplar { get; set; }
        public DbSet<Etiketler> Etiketler { get; set; }
        public DbSet<IletisimBilgileri> IletisimBilgileri { get; set; }
        public DbSet<Kullanicilar> Kullanicilar { get; set; }
        public DbSet<Sorular> Sorular { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Yorum> Yorum { get; set; }
    }
}
