//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public Kullanicilar()
        {
            this.Cevaplar = new HashSet<Cevaplar>();
            this.Sorular = new HashSet<Sorular>();
            this.Yorum = new HashSet<Yorum>();
            this.Cevaplar1 = new HashSet<Cevaplar>();
            this.Sorular1 = new HashSet<Sorular>();
        }
    
        public int KullaniciID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Mail { get; set; }
        public string Parola { get; set; }
        public string ProfilFoto { get; set; }
        public string Hakkimda { get; set; }
        public Nullable<int> IletisimBilgileriID { get; set; }
    
        public virtual ICollection<Cevaplar> Cevaplar { get; set; }
        public virtual IletisimBilgileri IletisimBilgileri { get; set; }
        public virtual ICollection<Sorular> Sorular { get; set; }
        public virtual ICollection<Yorum> Yorum { get; set; }
        public virtual ICollection<Cevaplar> Cevaplar1 { get; set; }
        public virtual ICollection<Sorular> Sorular1 { get; set; }
    }
}
