//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        public Sorular()
        {
            this.Cevaplar = new HashSet<Cevaplar>();
            this.Kullanicilar1 = new HashSet<Kullanicilar>();
            this.Etiketler = new HashSet<Etiketler>();
        }
    
        public int SoruID { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> BegeniSayisi { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<int> OnayCevapID { get; set; }
    
        public virtual ICollection<Cevaplar> Cevaplar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual ICollection<Kullanicilar> Kullanicilar1 { get; set; }
        public virtual ICollection<Etiketler> Etiketler { get; set; }
    }
}
